model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 8
    n_embed: 16384
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 8
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.75
        disc_num_layers: 2
        codebook_weight: 1.0

data:
  target: tools.data.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 5
    wrap: false
    train:
      target: controlled_img_modeling.data.imagenet.ImageNetTrain
      params:
        root: /scratch/anji/data/ImageNet/train/
        num_samples: 100000
        class_id_range_low: 0
        class_id_range_high: 99
        size: 256
    validation:
      target: controlled_img_modeling.data.imagenet.ImageNetValidation
      params:
        root: /scratch/anji/data/ImageNet/val/
        class_id_range_low: 0
        class_id_range_high: 99
        size: 256